sudo: false
language: python
python:
  - "3.6"
install:
- python --version
script:
- python --version
deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    on:
      tags: true
    user: ceball
    password: $PYPIPWD
